# Site settings
title: Presidential Innovation Fellows
description: "The Presidential Innovation Fellows program brings the principles, values, and practices of the innovation economy into government through the most effective agents of change we know: our people."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://staging.pif.gov" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap